#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="$2"


BOWERINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
if [ -f "./node_modules/bower/bin/bower" ]
then
  echo 'Bower already installed. Skipping...'
else
  npm install bower
fi
EOF
)

PACKAGESINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
if [ -f "./bower.json" ]
then
  ./node_modules/bower/bin/bower install --allow-root
else
  echo 'bower.json missing. Nothing to install...'
fi
EOF
)

GRUNTINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
if [ -f "./node_modules/grunt-cli/bin/grunt" ]
then
  echo 'grunt-cli already installed. Skipping...'
else
  npm install grunt-cli
fi
EOF
)

TASKSRUN=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
if [ -f "./Gruntfile.js" ]
then
  ./node_modules/grunt-cli/bin/grunt build
else
  echo 'Gruntfile.js is missing. No tasks to run...'
fi
EOF
)

echo '-----> Installing bower'
id=$(docker run -d $IMAGE /bin/bash -c "$BOWERINSTALL")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

echo '-----> Installing bower packages'
id=$(docker run -d $IMAGE /bin/bash -c "$PACKAGESINSTALL")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

echo '-----> Installing Grunt'
id=$(docker run -d $IMAGE /bin/bash -c "$GRUNTINSTALL")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

echo '-----> Running Grunt Tasks'
id=$(docker run -d $IMAGE /bin/bash -c "$TASKSRUN")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
