#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="$2"


GRUNTINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
npm install grunt-cli
EOF
)

TASKSRUN=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
./node_modules/grunt-cli/bin/grunt build
EOF
)

if [[ -f /app/Gruntfile.js ]]; then
  echo '-----> Installing Grunt'
  id=$(docker run -d $IMAGE /bin/bash -c "$GRUNTINSTALL")
  docker attach $id
  test $(docker wait $id) -eq 0
  docker commit $id $IMAGE > /dev/null
  echo '-----> Running Grunt Tasks'
  id=$(docker run -d $IMAGE /bin/bash -c "$TASKSRUN")
  docker attach $id
  test $(docker wait $id) -eq 0
  docker commit $id $IMAGE > /dev/null
fi
